services:
  mysql:
    image: mysql:8.0
    container_name: finance-control-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: finance_control
      MYSQL_USER: finance
      MYSQL_PASSWORD: itau-finance-control
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build: .
    container_name: finance-control-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql:3306/finance_control?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo
      DB_USERNAME: finance
      DB_PASSWORD: itau-finance-control
      DB_DRIVER: com.mysql.cj.jdbc.Driver
      API_KEY: aXRhw7o=
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:

