spring.application.name=finance-control-api
server.port=8080

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

api.security.api-key=${API_KEY:aXRhw7o=}

spring.datasource.url=${DB_URL:jdbc:h2:mem:financedb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.validation-timeout=3000

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=never
management.endpoint.metrics.enabled=true
management.metrics.enable.all=false
management.metrics.enable.http.server.requests=true
management.metrics.enable.application=true

