spring.application.name=finance-control-api
server.port=8080

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

api.security.api-key=${API_KEY:aXRhw7o=}

spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.validation-timeout=3000

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.locations=classpath:db/migration

management.endpoints.web.exposure.include=health,metrics
management.endpoint.health.show-details=never
management.endpoint.metrics.enabled=true
management.metrics.enable.all=false
management.metrics.enable.http.server.requests=true
management.metrics.enable.application=true

management.newrelic.metrics.export.api-key=${NEW_RELIC_API_KEY:}
management.newrelic.metrics.export.account-id=${NEW_RELIC_ACCOUNT_ID:}
management.newrelic.metrics.export.enabled=${NEW_RELIC_ENABLED:false}
management.newrelic.metrics.export.step=60s
